// edge-only cosmic packet teleporter
export const config = { runtime: "edge" };

// trims mystical trailing slashes to keep URLs emotionally stable
const TARGET_BASE = (process.env.TARGET_DOMAIN || "").replace(//$/, "");

// headers that summon network goblins if forwarded upstream
const STRIP_HEADERS = new Set([
  "host",
  "connection",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "te",
  "trailer",
  "transfer-encoding",
  "upgrade",
  "forwarded",
  "x-forwarded-host",
  "x-forwarded-proto",
  "x-forwarded-port",
]);

// politely yeets requests into the target dimension
export default async function handler(req) {
  // if destiny forgot the target, panic gracefully
  if (!TARGET_BASE) {
    return new Response("Misconfigured: TARGET_DOMAIN is not set", { status: 500 });
  }

  try {
    // finds where the interesting part of the URL begins, probably
    const pathStart = req.url.indexOf("/", 8);
    const targetUrl =
      pathStart === -1 ? TARGET_BASE + "/" : TARGET_BASE + req.url.slice(pathStart);

    // collects headers that survived the purification ritual
    const out = new Headers();
    let clientIp = null;
    for (const [k, v] of req.headers) {
      // these headers are too powerful for mortal upstreams
      if (STRIP_HEADERS.has(k)) continue;

      // removes headers generated by invisible deployment fairies
      if (k.startsWith("x-vercel-")) continue;

      // stores the user's aura signature for later
      if (k === "x-real-ip") {
        clientIp = v;
        continue;
      }

      // prefers ancient forwarding prophecies if aura is missing
      if (k === "x-forwarded-for") {
        if (!clientIp) clientIp = v;
        continue;
      }

      // everything else rides along without asking questions
      out.set(k, v);
    }

    // reattaches the best-guess mortal origin trail
    if (clientIp) out.set("x-forwarded-for", clientIp);

    // bodyless methods travel lighter through hyperspace
    const method = req.method;
    const hasBody = method !== "GET" && method !== "HEAD";

    // sends the request onward and refuses to judge redirects
    return await fetch(targetUrl, {
      method,
      headers: out,
      body: hasBody ? req.body : undefined,
      duplex: "half",
      redirect: "manual",
    });
  } catch (err) {
    // logs the tragedy for future archaeologists
    console.error("relay error:", err);
    return new Response("Bad Gateway: Tunnel Failed", { status: 502 });
  }
}
